const Type = {
  Items: 'items',
  Catalog: 'catalog',
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_INCREMENT: 'REMOVE_INCREMENT',
};

export default Type;
